/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppAndInstanceConditionEvaluatorAppOrInstance
 */
public class AppAndInstanceConditionEvaluatorAppOrInstanceTest {
    private final AppAndInstanceConditionEvaluatorAppOrInstance model = new AppAndInstanceConditionEvaluatorAppOrInstance();

    /**
     * Model tests for AppAndInstanceConditionEvaluatorAppOrInstance
     */
    @Test
    public void testAppAndInstanceConditionEvaluatorAppOrInstance() {
        // TODO: test AppAndInstanceConditionEvaluatorAppOrInstance
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
