/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicationCredentialsSigning;
import com.konfigthis.client.model.ApplicationCredentialsUsernameTemplate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicationCredentials
 */
public class ApplicationCredentialsTest {
    private final ApplicationCredentials model = new ApplicationCredentials();

    /**
     * Model tests for ApplicationCredentials
     */
    @Test
    public void testApplicationCredentials() {
        // TODO: test ApplicationCredentials
    }

    /**
     * Test the property 'signing'
     */
    @Test
    public void signingTest() {
        // TODO: test signing
    }

    /**
     * Test the property 'userNameTemplate'
     */
    @Test
    public void userNameTemplateTest() {
        // TODO: test userNameTemplate
    }

}
