/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicationVisibilityHide;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicationVisibility
 */
public class ApplicationVisibilityTest {
    private final ApplicationVisibility model = new ApplicationVisibility();

    /**
     * Model tests for ApplicationVisibility
     */
    @Test
    public void testApplicationVisibility() {
        // TODO: test ApplicationVisibility
    }

    /**
     * Test the property 'appLinks'
     */
    @Test
    public void appLinksTest() {
        // TODO: test appLinks
    }

    /**
     * Test the property 'autoLaunch'
     */
    @Test
    public void autoLaunchTest() {
        // TODO: test autoLaunch
    }

    /**
     * Test the property 'autoSubmitToolbar'
     */
    @Test
    public void autoSubmitToolbarTest() {
        // TODO: test autoSubmitToolbar
    }

    /**
     * Test the property 'hide'
     */
    @Test
    public void hideTest() {
        // TODO: test hide
    }

}
