/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BookmarkApplicationSettingsApplication;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BookmarkApplicationSettings
 */
public class BookmarkApplicationSettingsTest {
    private final BookmarkApplicationSettings model = new BookmarkApplicationSettings();

    /**
     * Model tests for BookmarkApplicationSettings
     */
    @Test
    public void testBookmarkApplicationSettings() {
        // TODO: test BookmarkApplicationSettings
    }

    /**
     * Test the property 'app'
     */
    @Test
    public void appTest() {
        // TODO: test app
    }

}
