/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MDMEnrollmentPolicyRuleCondition
 */
public class MDMEnrollmentPolicyRuleConditionTest {
    private final MDMEnrollmentPolicyRuleCondition model = new MDMEnrollmentPolicyRuleCondition();

    /**
     * Model tests for MDMEnrollmentPolicyRuleCondition
     */
    @Test
    public void testMDMEnrollmentPolicyRuleCondition() {
        // TODO: test MDMEnrollmentPolicyRuleCondition
    }

    /**
     * Test the property 'blockNonSafeAndroid'
     */
    @Test
    public void blockNonSafeAndroidTest() {
        // TODO: test blockNonSafeAndroid
    }

    /**
     * Test the property 'enrollment'
     */
    @Test
    public void enrollmentTest() {
        // TODO: test enrollment
    }

}
