/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MultifactorEnrollmentPolicyAuthenticatorSettingsConstraints;
import com.konfigthis.client.model.MultifactorEnrollmentPolicyAuthenticatorSettingsEnroll;
import com.konfigthis.client.model.MultifactorEnrollmentPolicyAuthenticatorType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MultifactorEnrollmentPolicyAuthenticatorSettings
 */
public class MultifactorEnrollmentPolicyAuthenticatorSettingsTest {
    private final MultifactorEnrollmentPolicyAuthenticatorSettings model = new MultifactorEnrollmentPolicyAuthenticatorSettings();

    /**
     * Model tests for MultifactorEnrollmentPolicyAuthenticatorSettings
     */
    @Test
    public void testMultifactorEnrollmentPolicyAuthenticatorSettings() {
        // TODO: test MultifactorEnrollmentPolicyAuthenticatorSettings
    }

    /**
     * Test the property 'constraints'
     */
    @Test
    public void constraintsTest() {
        // TODO: test constraints
    }

    /**
     * Test the property 'enroll'
     */
    @Test
    public void enrollTest() {
        // TODO: test enroll
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

}
