/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OAuth2ScopeConsentGrantSource
 */
public class OAuth2ScopeConsentGrantSourceTest {
    /**
     * Model tests for OAuth2ScopeConsentGrantSource
     */
    @Test
    public void testOAuth2ScopeConsentGrantSource() {
        // TODO: test OAuth2ScopeConsentGrantSource
    }

}
