/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PasswordPolicyPasswordSettingsLockout
 */
public class PasswordPolicyPasswordSettingsLockoutTest {
    private final PasswordPolicyPasswordSettingsLockout model = new PasswordPolicyPasswordSettingsLockout();

    /**
     * Model tests for PasswordPolicyPasswordSettingsLockout
     */
    @Test
    public void testPasswordPolicyPasswordSettingsLockout() {
        // TODO: test PasswordPolicyPasswordSettingsLockout
    }

    /**
     * Test the property 'autoUnlockMinutes'
     */
    @Test
    public void autoUnlockMinutesTest() {
        // TODO: test autoUnlockMinutes
    }

    /**
     * Test the property 'maxAttempts'
     */
    @Test
    public void maxAttemptsTest() {
        // TODO: test maxAttempts
    }

    /**
     * Test the property 'showLockoutFailures'
     */
    @Test
    public void showLockoutFailuresTest() {
        // TODO: test showLockoutFailures
    }

    /**
     * Test the property 'userLockoutNotificationChannels'
     */
    @Test
    public void userLockoutNotificationChannelsTest() {
        // TODO: test userLockoutNotificationChannels
    }

}
