/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PasswordPolicyRuleAction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PasswordPolicyRuleActions
 */
public class PasswordPolicyRuleActionsTest {
    private final PasswordPolicyRuleActions model = new PasswordPolicyRuleActions();

    /**
     * Model tests for PasswordPolicyRuleActions
     */
    @Test
    public void testPasswordPolicyRuleActions() {
        // TODO: test PasswordPolicyRuleActions
    }

    /**
     * Test the property 'passwordChange'
     */
    @Test
    public void passwordChangeTest() {
        // TODO: test passwordChange
    }

    /**
     * Test the property 'selfServicePasswordReset'
     */
    @Test
    public void selfServicePasswordResetTest() {
        // TODO: test selfServicePasswordReset
    }

    /**
     * Test the property 'selfServiceUnlock'
     */
    @Test
    public void selfServiceUnlockTest() {
        // TODO: test selfServiceUnlock
    }

}
