/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProtocolEndpoint;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProtocolEndpoints
 */
public class ProtocolEndpointsTest {
    private final ProtocolEndpoints model = new ProtocolEndpoints();

    /**
     * Model tests for ProtocolEndpoints
     */
    @Test
    public void testProtocolEndpoints() {
        // TODO: test ProtocolEndpoints
    }

    /**
     * Test the property 'acs'
     */
    @Test
    public void acsTest() {
        // TODO: test acs
    }

    /**
     * Test the property 'authorization'
     */
    @Test
    public void authorizationTest() {
        // TODO: test authorization
    }

    /**
     * Test the property 'jwks'
     */
    @Test
    public void jwksTest() {
        // TODO: test jwks
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'slo'
     */
    @Test
    public void sloTest() {
        // TODO: test slo
    }

    /**
     * Test the property 'sso'
     */
    @Test
    public void ssoTest() {
        // TODO: test sso
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'userInfo'
     */
    @Test
    public void userInfoTest() {
        // TODO: test userInfo
    }

}
