/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for U2fUserFactorProfile
 */
public class U2fUserFactorProfileTest {
    private final U2fUserFactorProfile model = new U2fUserFactorProfile();

    /**
     * Model tests for U2fUserFactorProfile
     */
    @Test
    public void testU2fUserFactorProfile() {
        // TODO: test U2fUserFactorProfile
    }

    /**
     * Test the property 'credentialId'
     */
    @Test
    public void credentialIdTest() {
        // TODO: test credentialId
    }

}
