/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AccessPolicyConstraints;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VerificationMethod
 */
public class VerificationMethodTest {
    private final VerificationMethod model = new VerificationMethod();

    /**
     * Model tests for VerificationMethod
     */
    @Test
    public void testVerificationMethod() {
        // TODO: test VerificationMethod
    }

    /**
     * Test the property 'constraints'
     */
    @Test
    public void constraintsTest() {
        // TODO: test constraints
    }

    /**
     * Test the property 'factorMode'
     */
    @Test
    public void factorModeTest() {
        // TODO: test factorMode
    }

    /**
     * Test the property 'inactivityPeriod'
     */
    @Test
    public void inactivityPeriodTest() {
        // TODO: test inactivityPeriod
    }

    /**
     * Test the property 'reauthenticateIn'
     */
    @Test
    public void reauthenticateInTest() {
        // TODO: test reauthenticateIn
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
