/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Brand
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Brand {
  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private Map<String, Object> links = null;

  public static final String SERIALIZED_NAME_AGREE_TO_CUSTOM_PRIVACY_POLICY = "agreeToCustomPrivacyPolicy";
  @SerializedName(SERIALIZED_NAME_AGREE_TO_CUSTOM_PRIVACY_POLICY)
  private Boolean agreeToCustomPrivacyPolicy;

  public static final String SERIALIZED_NAME_CUSTOM_PRIVACY_POLICY_URL = "customPrivacyPolicyUrl";
  @SerializedName(SERIALIZED_NAME_CUSTOM_PRIVACY_POLICY_URL)
  private String customPrivacyPolicyUrl;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_REMOVE_POWERED_BY_OKTA = "removePoweredByOkta";
  @SerializedName(SERIALIZED_NAME_REMOVE_POWERED_BY_OKTA)
  private Boolean removePoweredByOkta;

  public Brand() {
  }

  
  public Brand(
     Map<String, Object> links, 
     String id
  ) {
    this();
    this.links = links;
    this.id = id;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getLinks() {
    return links;
  }




  public Brand agreeToCustomPrivacyPolicy(Boolean agreeToCustomPrivacyPolicy) {
    
    
    
    
    this.agreeToCustomPrivacyPolicy = agreeToCustomPrivacyPolicy;
    return this;
  }

   /**
   * Get agreeToCustomPrivacyPolicy
   * @return agreeToCustomPrivacyPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAgreeToCustomPrivacyPolicy() {
    return agreeToCustomPrivacyPolicy;
  }


  public void setAgreeToCustomPrivacyPolicy(Boolean agreeToCustomPrivacyPolicy) {
    
    
    
    this.agreeToCustomPrivacyPolicy = agreeToCustomPrivacyPolicy;
  }


  public Brand customPrivacyPolicyUrl(String customPrivacyPolicyUrl) {
    
    
    
    
    this.customPrivacyPolicyUrl = customPrivacyPolicyUrl;
    return this;
  }

   /**
   * Get customPrivacyPolicyUrl
   * @return customPrivacyPolicyUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomPrivacyPolicyUrl() {
    return customPrivacyPolicyUrl;
  }


  public void setCustomPrivacyPolicyUrl(String customPrivacyPolicyUrl) {
    
    
    
    this.customPrivacyPolicyUrl = customPrivacyPolicyUrl;
  }


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }




  public Brand removePoweredByOkta(Boolean removePoweredByOkta) {
    
    
    
    
    this.removePoweredByOkta = removePoweredByOkta;
    return this;
  }

   /**
   * Get removePoweredByOkta
   * @return removePoweredByOkta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRemovePoweredByOkta() {
    return removePoweredByOkta;
  }


  public void setRemovePoweredByOkta(Boolean removePoweredByOkta) {
    
    
    
    this.removePoweredByOkta = removePoweredByOkta;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Brand instance itself
   */
  public Brand putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Brand brand = (Brand) o;
    return Objects.equals(this.links, brand.links) &&
        Objects.equals(this.agreeToCustomPrivacyPolicy, brand.agreeToCustomPrivacyPolicy) &&
        Objects.equals(this.customPrivacyPolicyUrl, brand.customPrivacyPolicyUrl) &&
        Objects.equals(this.id, brand.id) &&
        Objects.equals(this.removePoweredByOkta, brand.removePoweredByOkta)&&
        Objects.equals(this.additionalProperties, brand.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, agreeToCustomPrivacyPolicy, customPrivacyPolicyUrl, id, removePoweredByOkta, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Brand {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    agreeToCustomPrivacyPolicy: ").append(toIndentedString(agreeToCustomPrivacyPolicy)).append("\n");
    sb.append("    customPrivacyPolicyUrl: ").append(toIndentedString(customPrivacyPolicyUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    removePoweredByOkta: ").append(toIndentedString(removePoweredByOkta)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("_links");
    openapiFields.add("agreeToCustomPrivacyPolicy");
    openapiFields.add("customPrivacyPolicyUrl");
    openapiFields.add("id");
    openapiFields.add("removePoweredByOkta");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Brand
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Brand.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Brand is not found in the empty JSON string", Brand.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("customPrivacyPolicyUrl") != null && !jsonObj.get("customPrivacyPolicyUrl").isJsonNull()) && !jsonObj.get("customPrivacyPolicyUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customPrivacyPolicyUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customPrivacyPolicyUrl").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Brand.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Brand' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Brand> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Brand.class));

       return (TypeAdapter<T>) new TypeAdapter<Brand>() {
           @Override
           public void write(JsonWriter out, Brand value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Brand read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Brand instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Brand given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Brand
  * @throws IOException if the JSON string is invalid with respect to Brand
  */
  public static Brand fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Brand.class);
  }

 /**
  * Convert an instance of Brand to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

