/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets FactorType
 */
@JsonAdapter(FactorType.Adapter.class)public enum FactorType {
  
  CALL("call"),
  
  EMAIL("email"),
  
  HOTP("hotp"),
  
  PUSH("push"),
  
  QUESTION("question"),
  
  SIGNED_NONCE("signed_nonce"),
  
  SMS("sms"),
  
  TOKEN_HARDWARE("token:hardware"),
  
  TOKEN_HOTP("token:hotp"),
  
  TOKEN_SOFTWARE_TOTP("token:software:totp"),
  
  TOKEN("token"),
  
  U2F("u2f"),
  
  WEB("web"),
  
  WEBAUTHN("webauthn");

  private String value;

  FactorType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FactorType fromValue(String value) {
    for (FactorType b : FactorType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<FactorType> {
    @Override
    public void write(final JsonWriter jsonWriter, final FactorType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FactorType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FactorType.fromValue(value);
    }
  }
}

