/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LogAuthenticationProvider;
import com.konfigthis.client.model.LogCredentialProvider;
import com.konfigthis.client.model.LogCredentialType;
import com.konfigthis.client.model.LogIssuer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * LogAuthenticationContext
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LogAuthenticationContext {
  public static final String SERIALIZED_NAME_AUTHENTICATION_PROVIDER = "authenticationProvider";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_PROVIDER)
  private LogAuthenticationProvider authenticationProvider;

  public static final String SERIALIZED_NAME_AUTHENTICATION_STEP = "authenticationStep";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_STEP)
  private Integer authenticationStep;

  public static final String SERIALIZED_NAME_CREDENTIAL_PROVIDER = "credentialProvider";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL_PROVIDER)
  private LogCredentialProvider credentialProvider;

  public static final String SERIALIZED_NAME_CREDENTIAL_TYPE = "credentialType";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL_TYPE)
  private LogCredentialType credentialType;

  public static final String SERIALIZED_NAME_EXTERNAL_SESSION_ID = "externalSessionId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SESSION_ID)
  private String externalSessionId;

  public static final String SERIALIZED_NAME_INTERFACE = "interface";
  @SerializedName(SERIALIZED_NAME_INTERFACE)
  private String _interface;

  public static final String SERIALIZED_NAME_ISSUER = "issuer";
  @SerializedName(SERIALIZED_NAME_ISSUER)
  private LogIssuer issuer;

  public LogAuthenticationContext() {
  }

  
  public LogAuthenticationContext(
     Integer authenticationStep, 
     String externalSessionId, 
     String _interface
  ) {
    this();
    this.authenticationStep = authenticationStep;
    this.externalSessionId = externalSessionId;
    this._interface = _interface;
  }

  public LogAuthenticationContext authenticationProvider(LogAuthenticationProvider authenticationProvider) {
    
    
    
    
    this.authenticationProvider = authenticationProvider;
    return this;
  }

   /**
   * Get authenticationProvider
   * @return authenticationProvider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LogAuthenticationProvider getAuthenticationProvider() {
    return authenticationProvider;
  }


  public void setAuthenticationProvider(LogAuthenticationProvider authenticationProvider) {
    
    
    
    this.authenticationProvider = authenticationProvider;
  }


   /**
   * Get authenticationStep
   * @return authenticationStep
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAuthenticationStep() {
    return authenticationStep;
  }




  public LogAuthenticationContext credentialProvider(LogCredentialProvider credentialProvider) {
    
    
    
    
    this.credentialProvider = credentialProvider;
    return this;
  }

   /**
   * Get credentialProvider
   * @return credentialProvider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LogCredentialProvider getCredentialProvider() {
    return credentialProvider;
  }


  public void setCredentialProvider(LogCredentialProvider credentialProvider) {
    
    
    
    this.credentialProvider = credentialProvider;
  }


  public LogAuthenticationContext credentialType(LogCredentialType credentialType) {
    
    
    
    
    this.credentialType = credentialType;
    return this;
  }

   /**
   * Get credentialType
   * @return credentialType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LogCredentialType getCredentialType() {
    return credentialType;
  }


  public void setCredentialType(LogCredentialType credentialType) {
    
    
    
    this.credentialType = credentialType;
  }


   /**
   * Get externalSessionId
   * @return externalSessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExternalSessionId() {
    return externalSessionId;
  }




   /**
   * Get _interface
   * @return _interface
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInterface() {
    return _interface;
  }




  public LogAuthenticationContext issuer(LogIssuer issuer) {
    
    
    
    
    this.issuer = issuer;
    return this;
  }

   /**
   * Get issuer
   * @return issuer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LogIssuer getIssuer() {
    return issuer;
  }


  public void setIssuer(LogIssuer issuer) {
    
    
    
    this.issuer = issuer;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LogAuthenticationContext instance itself
   */
  public LogAuthenticationContext putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogAuthenticationContext logAuthenticationContext = (LogAuthenticationContext) o;
    return Objects.equals(this.authenticationProvider, logAuthenticationContext.authenticationProvider) &&
        Objects.equals(this.authenticationStep, logAuthenticationContext.authenticationStep) &&
        Objects.equals(this.credentialProvider, logAuthenticationContext.credentialProvider) &&
        Objects.equals(this.credentialType, logAuthenticationContext.credentialType) &&
        Objects.equals(this.externalSessionId, logAuthenticationContext.externalSessionId) &&
        Objects.equals(this._interface, logAuthenticationContext._interface) &&
        Objects.equals(this.issuer, logAuthenticationContext.issuer)&&
        Objects.equals(this.additionalProperties, logAuthenticationContext.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationProvider, authenticationStep, credentialProvider, credentialType, externalSessionId, _interface, issuer, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogAuthenticationContext {\n");
    sb.append("    authenticationProvider: ").append(toIndentedString(authenticationProvider)).append("\n");
    sb.append("    authenticationStep: ").append(toIndentedString(authenticationStep)).append("\n");
    sb.append("    credentialProvider: ").append(toIndentedString(credentialProvider)).append("\n");
    sb.append("    credentialType: ").append(toIndentedString(credentialType)).append("\n");
    sb.append("    externalSessionId: ").append(toIndentedString(externalSessionId)).append("\n");
    sb.append("    _interface: ").append(toIndentedString(_interface)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("authenticationProvider");
    openapiFields.add("authenticationStep");
    openapiFields.add("credentialProvider");
    openapiFields.add("credentialType");
    openapiFields.add("externalSessionId");
    openapiFields.add("interface");
    openapiFields.add("issuer");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LogAuthenticationContext
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LogAuthenticationContext.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LogAuthenticationContext is not found in the empty JSON string", LogAuthenticationContext.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("externalSessionId") != null && !jsonObj.get("externalSessionId").isJsonNull()) && !jsonObj.get("externalSessionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `externalSessionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalSessionId").toString()));
      }
      if ((jsonObj.get("interface") != null && !jsonObj.get("interface").isJsonNull()) && !jsonObj.get("interface").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `interface` to be a primitive type in the JSON string but got `%s`", jsonObj.get("interface").toString()));
      }
      // validate the optional field `issuer`
      if (jsonObj.get("issuer") != null && !jsonObj.get("issuer").isJsonNull()) {
        LogIssuer.validateJsonObject(jsonObj.getAsJsonObject("issuer"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LogAuthenticationContext.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LogAuthenticationContext' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LogAuthenticationContext> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LogAuthenticationContext.class));

       return (TypeAdapter<T>) new TypeAdapter<LogAuthenticationContext>() {
           @Override
           public void write(JsonWriter out, LogAuthenticationContext value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LogAuthenticationContext read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LogAuthenticationContext instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LogAuthenticationContext given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LogAuthenticationContext
  * @throws IOException if the JSON string is invalid with respect to LogAuthenticationContext
  */
  public static LogAuthenticationContext fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LogAuthenticationContext.class);
  }

 /**
  * Convert an instance of LogAuthenticationContext to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

