/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets OAuthGrantType
 */
@JsonAdapter(OAuthGrantType.Adapter.class)public enum OAuthGrantType {
  
  AUTHORIZATION_CODE("authorization_code"),
  
  IMPLICIT("implicit"),
  
  PASSWORD("password"),
  
  REFRESH_TOKEN("refresh_token"),
  
  CLIENT_CREDENTIALS("client_credentials"),
  
  SAML2_BEARER("saml2_bearer"),
  
  DEVICE_CODE("device_code"),
  
  TOKEN_EXCHANGE("token_exchange"),
  
  INTERACTION_CODE("interaction_code");

  private String value;

  OAuthGrantType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OAuthGrantType fromValue(String value) {
    for (OAuthGrantType b : OAuthGrantType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OAuthGrantType> {
    @Override
    public void write(final JsonWriter jsonWriter, final OAuthGrantType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OAuthGrantType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OAuthGrantType.fromValue(value);
    }
  }
}

