/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PasswordPolicyPasswordSettingsAge;
import com.konfigthis.client.model.PasswordPolicyPasswordSettingsComplexity;
import com.konfigthis.client.model.PasswordPolicyPasswordSettingsLockout;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PasswordPolicyPasswordSettings
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PasswordPolicyPasswordSettings {
  public static final String SERIALIZED_NAME_AGE = "age";
  @SerializedName(SERIALIZED_NAME_AGE)
  private PasswordPolicyPasswordSettingsAge age;

  public static final String SERIALIZED_NAME_COMPLEXITY = "complexity";
  @SerializedName(SERIALIZED_NAME_COMPLEXITY)
  private PasswordPolicyPasswordSettingsComplexity complexity;

  public static final String SERIALIZED_NAME_LOCKOUT = "lockout";
  @SerializedName(SERIALIZED_NAME_LOCKOUT)
  private PasswordPolicyPasswordSettingsLockout lockout;

  public PasswordPolicyPasswordSettings() {
  }

  public PasswordPolicyPasswordSettings age(PasswordPolicyPasswordSettingsAge age) {
    
    
    
    
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PasswordPolicyPasswordSettingsAge getAge() {
    return age;
  }


  public void setAge(PasswordPolicyPasswordSettingsAge age) {
    
    
    
    this.age = age;
  }


  public PasswordPolicyPasswordSettings complexity(PasswordPolicyPasswordSettingsComplexity complexity) {
    
    
    
    
    this.complexity = complexity;
    return this;
  }

   /**
   * Get complexity
   * @return complexity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PasswordPolicyPasswordSettingsComplexity getComplexity() {
    return complexity;
  }


  public void setComplexity(PasswordPolicyPasswordSettingsComplexity complexity) {
    
    
    
    this.complexity = complexity;
  }


  public PasswordPolicyPasswordSettings lockout(PasswordPolicyPasswordSettingsLockout lockout) {
    
    
    
    
    this.lockout = lockout;
    return this;
  }

   /**
   * Get lockout
   * @return lockout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PasswordPolicyPasswordSettingsLockout getLockout() {
    return lockout;
  }


  public void setLockout(PasswordPolicyPasswordSettingsLockout lockout) {
    
    
    
    this.lockout = lockout;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PasswordPolicyPasswordSettings instance itself
   */
  public PasswordPolicyPasswordSettings putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordPolicyPasswordSettings passwordPolicyPasswordSettings = (PasswordPolicyPasswordSettings) o;
    return Objects.equals(this.age, passwordPolicyPasswordSettings.age) &&
        Objects.equals(this.complexity, passwordPolicyPasswordSettings.complexity) &&
        Objects.equals(this.lockout, passwordPolicyPasswordSettings.lockout)&&
        Objects.equals(this.additionalProperties, passwordPolicyPasswordSettings.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(age, complexity, lockout, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordPolicyPasswordSettings {\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    complexity: ").append(toIndentedString(complexity)).append("\n");
    sb.append("    lockout: ").append(toIndentedString(lockout)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("age");
    openapiFields.add("complexity");
    openapiFields.add("lockout");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PasswordPolicyPasswordSettings
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PasswordPolicyPasswordSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PasswordPolicyPasswordSettings is not found in the empty JSON string", PasswordPolicyPasswordSettings.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `age`
      if (jsonObj.get("age") != null && !jsonObj.get("age").isJsonNull()) {
        PasswordPolicyPasswordSettingsAge.validateJsonObject(jsonObj.getAsJsonObject("age"));
      }
      // validate the optional field `complexity`
      if (jsonObj.get("complexity") != null && !jsonObj.get("complexity").isJsonNull()) {
        PasswordPolicyPasswordSettingsComplexity.validateJsonObject(jsonObj.getAsJsonObject("complexity"));
      }
      // validate the optional field `lockout`
      if (jsonObj.get("lockout") != null && !jsonObj.get("lockout").isJsonNull()) {
        PasswordPolicyPasswordSettingsLockout.validateJsonObject(jsonObj.getAsJsonObject("lockout"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PasswordPolicyPasswordSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PasswordPolicyPasswordSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PasswordPolicyPasswordSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PasswordPolicyPasswordSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<PasswordPolicyPasswordSettings>() {
           @Override
           public void write(JsonWriter out, PasswordPolicyPasswordSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PasswordPolicyPasswordSettings read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PasswordPolicyPasswordSettings instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PasswordPolicyPasswordSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PasswordPolicyPasswordSettings
  * @throws IOException if the JSON string is invalid with respect to PasswordPolicyPasswordSettings
  */
  public static PasswordPolicyPasswordSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PasswordPolicyPasswordSettings.class);
  }

 /**
  * Convert an instance of PasswordPolicyPasswordSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

