/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PasswordCredentialHashAlgorithm;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PasswordCredentialHash
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PasswordCredentialHash {
  public static final String SERIALIZED_NAME_ALGORITHM = "algorithm";
  @SerializedName(SERIALIZED_NAME_ALGORITHM)
  private PasswordCredentialHashAlgorithm algorithm;

  public static final String SERIALIZED_NAME_SALT = "salt";
  @SerializedName(SERIALIZED_NAME_SALT)
  private String salt;

  public static final String SERIALIZED_NAME_SALT_ORDER = "saltOrder";
  @SerializedName(SERIALIZED_NAME_SALT_ORDER)
  private String saltOrder;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_WORK_FACTOR = "workFactor";
  @SerializedName(SERIALIZED_NAME_WORK_FACTOR)
  private Integer workFactor;

  public PasswordCredentialHash() {
  }

  public PasswordCredentialHash algorithm(PasswordCredentialHashAlgorithm algorithm) {
    
    
    
    
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PasswordCredentialHashAlgorithm getAlgorithm() {
    return algorithm;
  }


  public void setAlgorithm(PasswordCredentialHashAlgorithm algorithm) {
    
    
    
    this.algorithm = algorithm;
  }


  public PasswordCredentialHash salt(String salt) {
    
    
    
    
    this.salt = salt;
    return this;
  }

   /**
   * Get salt
   * @return salt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSalt() {
    return salt;
  }


  public void setSalt(String salt) {
    
    
    
    this.salt = salt;
  }


  public PasswordCredentialHash saltOrder(String saltOrder) {
    
    
    
    
    this.saltOrder = saltOrder;
    return this;
  }

   /**
   * Get saltOrder
   * @return saltOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSaltOrder() {
    return saltOrder;
  }


  public void setSaltOrder(String saltOrder) {
    
    
    
    this.saltOrder = saltOrder;
  }


  public PasswordCredentialHash value(String value) {
    
    
    
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    
    
    
    this.value = value;
  }


  public PasswordCredentialHash workFactor(Integer workFactor) {
    
    
    
    
    this.workFactor = workFactor;
    return this;
  }

   /**
   * Get workFactor
   * @return workFactor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWorkFactor() {
    return workFactor;
  }


  public void setWorkFactor(Integer workFactor) {
    
    
    
    this.workFactor = workFactor;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PasswordCredentialHash instance itself
   */
  public PasswordCredentialHash putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordCredentialHash passwordCredentialHash = (PasswordCredentialHash) o;
    return Objects.equals(this.algorithm, passwordCredentialHash.algorithm) &&
        Objects.equals(this.salt, passwordCredentialHash.salt) &&
        Objects.equals(this.saltOrder, passwordCredentialHash.saltOrder) &&
        Objects.equals(this.value, passwordCredentialHash.value) &&
        Objects.equals(this.workFactor, passwordCredentialHash.workFactor)&&
        Objects.equals(this.additionalProperties, passwordCredentialHash.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithm, salt, saltOrder, value, workFactor, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordCredentialHash {\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    saltOrder: ").append(toIndentedString(saltOrder)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    workFactor: ").append(toIndentedString(workFactor)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("algorithm");
    openapiFields.add("salt");
    openapiFields.add("saltOrder");
    openapiFields.add("value");
    openapiFields.add("workFactor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PasswordCredentialHash
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PasswordCredentialHash.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PasswordCredentialHash is not found in the empty JSON string", PasswordCredentialHash.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("salt") != null && !jsonObj.get("salt").isJsonNull()) && !jsonObj.get("salt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `salt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("salt").toString()));
      }
      if ((jsonObj.get("saltOrder") != null && !jsonObj.get("saltOrder").isJsonNull()) && !jsonObj.get("saltOrder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `saltOrder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("saltOrder").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PasswordCredentialHash.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PasswordCredentialHash' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PasswordCredentialHash> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PasswordCredentialHash.class));

       return (TypeAdapter<T>) new TypeAdapter<PasswordCredentialHash>() {
           @Override
           public void write(JsonWriter out, PasswordCredentialHash value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PasswordCredentialHash read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PasswordCredentialHash instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PasswordCredentialHash given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PasswordCredentialHash
  * @throws IOException if the JSON string is invalid with respect to PasswordCredentialHash
  */
  public static PasswordCredentialHash fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PasswordCredentialHash.class);
  }

 /**
  * Convert an instance of PasswordCredentialHash to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

