/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PasswordPolicyPasswordSettingsAge
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PasswordPolicyPasswordSettingsAge {
  public static final String SERIALIZED_NAME_EXPIRE_WARN_DAYS = "expireWarnDays";
  @SerializedName(SERIALIZED_NAME_EXPIRE_WARN_DAYS)
  private Integer expireWarnDays = 0;

  public static final String SERIALIZED_NAME_HISTORY_COUNT = "historyCount";
  @SerializedName(SERIALIZED_NAME_HISTORY_COUNT)
  private Integer historyCount = 0;

  public static final String SERIALIZED_NAME_MAX_AGE_DAYS = "maxAgeDays";
  @SerializedName(SERIALIZED_NAME_MAX_AGE_DAYS)
  private Integer maxAgeDays = 0;

  public static final String SERIALIZED_NAME_MIN_AGE_MINUTES = "minAgeMinutes";
  @SerializedName(SERIALIZED_NAME_MIN_AGE_MINUTES)
  private Integer minAgeMinutes = 0;

  public PasswordPolicyPasswordSettingsAge() {
  }

  public PasswordPolicyPasswordSettingsAge expireWarnDays(Integer expireWarnDays) {
    
    
    
    
    this.expireWarnDays = expireWarnDays;
    return this;
  }

   /**
   * Get expireWarnDays
   * @return expireWarnDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getExpireWarnDays() {
    return expireWarnDays;
  }


  public void setExpireWarnDays(Integer expireWarnDays) {
    
    
    
    this.expireWarnDays = expireWarnDays;
  }


  public PasswordPolicyPasswordSettingsAge historyCount(Integer historyCount) {
    
    
    
    
    this.historyCount = historyCount;
    return this;
  }

   /**
   * Get historyCount
   * @return historyCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getHistoryCount() {
    return historyCount;
  }


  public void setHistoryCount(Integer historyCount) {
    
    
    
    this.historyCount = historyCount;
  }


  public PasswordPolicyPasswordSettingsAge maxAgeDays(Integer maxAgeDays) {
    
    
    
    
    this.maxAgeDays = maxAgeDays;
    return this;
  }

   /**
   * Get maxAgeDays
   * @return maxAgeDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getMaxAgeDays() {
    return maxAgeDays;
  }


  public void setMaxAgeDays(Integer maxAgeDays) {
    
    
    
    this.maxAgeDays = maxAgeDays;
  }


  public PasswordPolicyPasswordSettingsAge minAgeMinutes(Integer minAgeMinutes) {
    
    
    
    
    this.minAgeMinutes = minAgeMinutes;
    return this;
  }

   /**
   * Get minAgeMinutes
   * @return minAgeMinutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getMinAgeMinutes() {
    return minAgeMinutes;
  }


  public void setMinAgeMinutes(Integer minAgeMinutes) {
    
    
    
    this.minAgeMinutes = minAgeMinutes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PasswordPolicyPasswordSettingsAge instance itself
   */
  public PasswordPolicyPasswordSettingsAge putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordPolicyPasswordSettingsAge passwordPolicyPasswordSettingsAge = (PasswordPolicyPasswordSettingsAge) o;
    return Objects.equals(this.expireWarnDays, passwordPolicyPasswordSettingsAge.expireWarnDays) &&
        Objects.equals(this.historyCount, passwordPolicyPasswordSettingsAge.historyCount) &&
        Objects.equals(this.maxAgeDays, passwordPolicyPasswordSettingsAge.maxAgeDays) &&
        Objects.equals(this.minAgeMinutes, passwordPolicyPasswordSettingsAge.minAgeMinutes)&&
        Objects.equals(this.additionalProperties, passwordPolicyPasswordSettingsAge.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expireWarnDays, historyCount, maxAgeDays, minAgeMinutes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordPolicyPasswordSettingsAge {\n");
    sb.append("    expireWarnDays: ").append(toIndentedString(expireWarnDays)).append("\n");
    sb.append("    historyCount: ").append(toIndentedString(historyCount)).append("\n");
    sb.append("    maxAgeDays: ").append(toIndentedString(maxAgeDays)).append("\n");
    sb.append("    minAgeMinutes: ").append(toIndentedString(minAgeMinutes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("expireWarnDays");
    openapiFields.add("historyCount");
    openapiFields.add("maxAgeDays");
    openapiFields.add("minAgeMinutes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PasswordPolicyPasswordSettingsAge
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PasswordPolicyPasswordSettingsAge.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PasswordPolicyPasswordSettingsAge is not found in the empty JSON string", PasswordPolicyPasswordSettingsAge.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PasswordPolicyPasswordSettingsAge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PasswordPolicyPasswordSettingsAge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PasswordPolicyPasswordSettingsAge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PasswordPolicyPasswordSettingsAge.class));

       return (TypeAdapter<T>) new TypeAdapter<PasswordPolicyPasswordSettingsAge>() {
           @Override
           public void write(JsonWriter out, PasswordPolicyPasswordSettingsAge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PasswordPolicyPasswordSettingsAge read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PasswordPolicyPasswordSettingsAge instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PasswordPolicyPasswordSettingsAge given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PasswordPolicyPasswordSettingsAge
  * @throws IOException if the JSON string is invalid with respect to PasswordPolicyPasswordSettingsAge
  */
  public static PasswordPolicyPasswordSettingsAge fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PasswordPolicyPasswordSettingsAge.class);
  }

 /**
  * Convert an instance of PasswordPolicyPasswordSettingsAge to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

