/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProtocolEndpoint;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ProtocolEndpoints
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProtocolEndpoints {
  public static final String SERIALIZED_NAME_ACS = "acs";
  @SerializedName(SERIALIZED_NAME_ACS)
  private ProtocolEndpoint acs;

  public static final String SERIALIZED_NAME_AUTHORIZATION = "authorization";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION)
  private ProtocolEndpoint authorization;

  public static final String SERIALIZED_NAME_JWKS = "jwks";
  @SerializedName(SERIALIZED_NAME_JWKS)
  private ProtocolEndpoint jwks;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private ProtocolEndpoint metadata;

  public static final String SERIALIZED_NAME_SLO = "slo";
  @SerializedName(SERIALIZED_NAME_SLO)
  private ProtocolEndpoint slo;

  public static final String SERIALIZED_NAME_SSO = "sso";
  @SerializedName(SERIALIZED_NAME_SSO)
  private ProtocolEndpoint sso;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private ProtocolEndpoint token;

  public static final String SERIALIZED_NAME_USER_INFO = "userInfo";
  @SerializedName(SERIALIZED_NAME_USER_INFO)
  private ProtocolEndpoint userInfo;

  public ProtocolEndpoints() {
  }

  public ProtocolEndpoints acs(ProtocolEndpoint acs) {
    
    
    
    
    this.acs = acs;
    return this;
  }

   /**
   * Get acs
   * @return acs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getAcs() {
    return acs;
  }


  public void setAcs(ProtocolEndpoint acs) {
    
    
    
    this.acs = acs;
  }


  public ProtocolEndpoints authorization(ProtocolEndpoint authorization) {
    
    
    
    
    this.authorization = authorization;
    return this;
  }

   /**
   * Get authorization
   * @return authorization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getAuthorization() {
    return authorization;
  }


  public void setAuthorization(ProtocolEndpoint authorization) {
    
    
    
    this.authorization = authorization;
  }


  public ProtocolEndpoints jwks(ProtocolEndpoint jwks) {
    
    
    
    
    this.jwks = jwks;
    return this;
  }

   /**
   * Get jwks
   * @return jwks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getJwks() {
    return jwks;
  }


  public void setJwks(ProtocolEndpoint jwks) {
    
    
    
    this.jwks = jwks;
  }


  public ProtocolEndpoints metadata(ProtocolEndpoint metadata) {
    
    
    
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getMetadata() {
    return metadata;
  }


  public void setMetadata(ProtocolEndpoint metadata) {
    
    
    
    this.metadata = metadata;
  }


  public ProtocolEndpoints slo(ProtocolEndpoint slo) {
    
    
    
    
    this.slo = slo;
    return this;
  }

   /**
   * Get slo
   * @return slo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getSlo() {
    return slo;
  }


  public void setSlo(ProtocolEndpoint slo) {
    
    
    
    this.slo = slo;
  }


  public ProtocolEndpoints sso(ProtocolEndpoint sso) {
    
    
    
    
    this.sso = sso;
    return this;
  }

   /**
   * Get sso
   * @return sso
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getSso() {
    return sso;
  }


  public void setSso(ProtocolEndpoint sso) {
    
    
    
    this.sso = sso;
  }


  public ProtocolEndpoints token(ProtocolEndpoint token) {
    
    
    
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getToken() {
    return token;
  }


  public void setToken(ProtocolEndpoint token) {
    
    
    
    this.token = token;
  }


  public ProtocolEndpoints userInfo(ProtocolEndpoint userInfo) {
    
    
    
    
    this.userInfo = userInfo;
    return this;
  }

   /**
   * Get userInfo
   * @return userInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProtocolEndpoint getUserInfo() {
    return userInfo;
  }


  public void setUserInfo(ProtocolEndpoint userInfo) {
    
    
    
    this.userInfo = userInfo;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProtocolEndpoints instance itself
   */
  public ProtocolEndpoints putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtocolEndpoints protocolEndpoints = (ProtocolEndpoints) o;
    return Objects.equals(this.acs, protocolEndpoints.acs) &&
        Objects.equals(this.authorization, protocolEndpoints.authorization) &&
        Objects.equals(this.jwks, protocolEndpoints.jwks) &&
        Objects.equals(this.metadata, protocolEndpoints.metadata) &&
        Objects.equals(this.slo, protocolEndpoints.slo) &&
        Objects.equals(this.sso, protocolEndpoints.sso) &&
        Objects.equals(this.token, protocolEndpoints.token) &&
        Objects.equals(this.userInfo, protocolEndpoints.userInfo)&&
        Objects.equals(this.additionalProperties, protocolEndpoints.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acs, authorization, jwks, metadata, slo, sso, token, userInfo, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtocolEndpoints {\n");
    sb.append("    acs: ").append(toIndentedString(acs)).append("\n");
    sb.append("    authorization: ").append(toIndentedString(authorization)).append("\n");
    sb.append("    jwks: ").append(toIndentedString(jwks)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    slo: ").append(toIndentedString(slo)).append("\n");
    sb.append("    sso: ").append(toIndentedString(sso)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    userInfo: ").append(toIndentedString(userInfo)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("acs");
    openapiFields.add("authorization");
    openapiFields.add("jwks");
    openapiFields.add("metadata");
    openapiFields.add("slo");
    openapiFields.add("sso");
    openapiFields.add("token");
    openapiFields.add("userInfo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProtocolEndpoints
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProtocolEndpoints.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProtocolEndpoints is not found in the empty JSON string", ProtocolEndpoints.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `acs`
      if (jsonObj.get("acs") != null && !jsonObj.get("acs").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("acs"));
      }
      // validate the optional field `authorization`
      if (jsonObj.get("authorization") != null && !jsonObj.get("authorization").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("authorization"));
      }
      // validate the optional field `jwks`
      if (jsonObj.get("jwks") != null && !jsonObj.get("jwks").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("jwks"));
      }
      // validate the optional field `metadata`
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("metadata"));
      }
      // validate the optional field `slo`
      if (jsonObj.get("slo") != null && !jsonObj.get("slo").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("slo"));
      }
      // validate the optional field `sso`
      if (jsonObj.get("sso") != null && !jsonObj.get("sso").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("sso"));
      }
      // validate the optional field `token`
      if (jsonObj.get("token") != null && !jsonObj.get("token").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("token"));
      }
      // validate the optional field `userInfo`
      if (jsonObj.get("userInfo") != null && !jsonObj.get("userInfo").isJsonNull()) {
        ProtocolEndpoint.validateJsonObject(jsonObj.getAsJsonObject("userInfo"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProtocolEndpoints.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProtocolEndpoints' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProtocolEndpoints> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProtocolEndpoints.class));

       return (TypeAdapter<T>) new TypeAdapter<ProtocolEndpoints>() {
           @Override
           public void write(JsonWriter out, ProtocolEndpoints value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProtocolEndpoints read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProtocolEndpoints instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProtocolEndpoints given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProtocolEndpoints
  * @throws IOException if the JSON string is invalid with respect to ProtocolEndpoints
  */
  public static ProtocolEndpoints fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProtocolEndpoints.class);
  }

 /**
  * Convert an instance of ProtocolEndpoints to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

