/*
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.LogEvent;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogApi
 */
@Disabled
public class LogApiTest {

    private static LogApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new LogApi(apiClient);
    }

    /**
     * Fetch a list of events from your Okta organization system log.
     *
     * The Okta System Log API provides read access to your organization’s system log. This API provides more functionality than the Events API
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListEventsTest() throws ApiException {
        OffsetDateTime since = null;
        OffsetDateTime until = null;
        String filter = null;
        String q = null;
        Integer limit = null;
        String sortOrder = null;
        String after = null;
        List<LogEvent> response = api.getListEvents()
                .since(since)
                .until(until)
                .filter(filter)
                .q(q)
                .limit(limit)
                .sortOrder(sortOrder)
                .after(after)
                .execute();
        // TODO: test validations
    }

}
